apiVersion: v1
kind: Pod
metadata:
  name: nodehelloasia.example.com
  lables:
    app: helloworld
spec:
  containers:
  - name: kubernetes
    image: jhayash55/express-api
    ports:
    - containerPort: 3000
